FROM python:3.11 as server-step

COPY ./data ./data
WORKDIR /app

COPY requirements.txt api/app.py api/config.yaml ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV development
EXPOSE 5000
CMD ["flask", "run","--host=0.0.0.0"]