services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: phonon-visualizer-server
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: phonon-visualizer-client
    ports:
      - "8080:80"