FROM python:3.11 as server-step

COPY ./data ./data
WORKDIR /app

COPY requirements.txt api/app.py api/config.yaml ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production
EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]

